# action.yml
name: 'Go Release Binaries'
author: 'Jay Zhang <wangyoucao577@gmail.com>'
description: 'Build and Release Go Binaries to GitHub Release Assets'
inputs:
  github_token:
    description: 'GITHUB_TOKEN for uploading releases to Github asserts.'
    required: true
    default: ''
  goos:
    description: 'GOOS is the running programs operating system target: one of darwin, freebsd, linux, and so on.'
    required: true
    default: ''
  goarch:
    description: 'GOARCH is the running programs architecture target: one of 386, amd64, arm, s390x, and so on.'
    required: true
    default: ''
  goversion:
    description: 'The `Go` compiler version.'
    required: false
    default: ''
  build_flags:
    description: 'Additional arguments to pass the go build command.'
    required: false
    default: ''
  ldflags:
    description: 'Values to provide to the -ldflags argument'
    required: false
    default: ''
  project_path:
    description: 'Where to run `go build .`'
    required: false
    default: '.'
  binary_name:  
    description: 'Specify another binary name if do not want to use repository basename'
    required: false
    default: ''
  pre_command:
    description: 'Extra command that will be executed before `go build`, may for solving dependency'
    required: false
    default: ''
  build_command:
    description: 'The actual command to build binary, typically `go build`.'
    required: false
    default: 'go build'
  executable_compression:
    description: 'Compression executable binary by some third-party tools. Only `upx` is supported at the moment.'
    required: false
    default: ''
  extra_files:
    description: 'Extra files that will be packaged into artifacts either.'
    required: false
    default: ''
  md5sum:
    description: 'Publish `.md5` along with artifacts.'
    required: false
    default: 'TRUE'
  sha256sum:
    description: 'Publish `.sha256` along with artifacts.'
    required: false
    default: 'FALSE'
  release_tag:
    description: 'Upload binaries to specified release page that indicated by Git tag.'
    required: false
    default: ''
  overwrite:
    description: "Overwrite asset if it's already exist."
    required: false
    default: 'FALSE'
  asset_name:  
    description: 'Customize asset name if do not want to use the default format.'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'docker://ghcr.io/wangyoucao577/go-release-action:v1.20'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.goos }}
    - ${{ inputs.goarch }}
    - ${{ inputs.goversion }}
    - ${{ inputs.build_flags}}
    - ${{ inputs.ldflags }}
    - ${{ inputs.project_path }}
    - ${{ inputs.binary_name }}
    - ${{ inputs.pre_command }}
    - ${{ inputs.build_command }}
    - ${{ inputs.executable_compression }}
    - ${{ inputs.extra_files }}
    - ${{ inputs.md5sum }}
    - ${{ inputs.sha256sum }}
    - ${{ inputs.release_tag }}
    - ${{ inputs.overwrite }}
    - ${{ inputs.asset_name }}

branding:
  icon: 'package'  
  color: 'blue'
