name: PR Build 

on: 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  build:
    name: PR Build & Check

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Environment Printer
      uses: managedkaos/print-env@v1.0

    - run: docker build . 
